<?php

/**
 * @file
 * Contains more_field_formatters.module.
 * Copyright 2017 Palantir.net, Inc.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function more_field_formatters_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the more_field_formatters module.
    case 'help.page.more_field_formatters':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Additional formatters for Drupal 8 fields.') . '</p>';
      return $output;

    default:
  }
}
